import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import router from "./router";
import axios from "@/api/axios";
const app = createApp(App);
app.config.globalProperties.$axios = axios;
createApp(App).use(router).use(ElementPlus).mount("#app");
